name: shop_mobx
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.6+1
  cupertino_icons: ^1.0.2
  path_provider: 2.0.10
  intl: 0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.6+1
  build_runner: ^2.1.10
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
